IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LookupTypeItems' AND COLUMN_NAME = 'IsDeleted')
BEGIN
	ALTER TABLE LookupTypeItems ADD [IsDeleted] [bit] NOT NULL DEFAULT(0)
END
GO