IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GuestBookingDetails' AND COLUMN_NAME = 'CheckedInDateTime')
BEGIN
	ALTER TABLE GuestBookingDetails ADD CheckedInDateTime DATETIME NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GuestBookingDetails' AND COLUMN_NAME = 'CheckedInBy')
BEGIN
	ALTER TABLE GuestBookingDetails ADD CheckedInBy nvarchar(256)
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GuestBookingDetails' AND COLUMN_NAME = 'CheckedOutDateTime')
BEGIN
	ALTER TABLE GuestBookingDetails ADD CheckedOutDateTime DATETIME NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GuestBookingDetails' AND COLUMN_NAME = 'CheckedOutBy')
BEGIN
	ALTER TABLE GuestBookingDetails ADD CheckedOutBy nvarchar(256)
END
GO