IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'IncBuklod')
BEGIN
	CREATE TABLE [dbo].[IncBuklod](
		[Id] [int] IDENTITY(1,1) NOT NULL,
		[LastName] [VARCHAR](100) NOT NULL,
		[FirstName] [VARCHAR](100) NOT NULL,
		[Purok] [INT] NOT NULL DEFAULT(0),
		[Grupo] [INT] NOT NULL DEFAULT(0),
		[Mobile] [VARCHAR(20)] NULL,
		[Anniversary] [DATETIME] NULL,
		[Birthday] [DATETIME] NULL,
		[IsDeleted] [bit] not null default(0),
		CONSTRAINT [PK_IncBuklod] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO