IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AspNetUsers' AND COLUMN_NAME = 'IsPaidPushNotification')
BEGIN
	ALTER TABLE AspNetUsers ADD IsPaidPushNotification BIT NOT NULL DEFAULT(0)
END
GO
