IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RentArrears' AND COLUMN_NAME = 'ProcessedDateTimeUtc')
BEGIN
	ALTER TABLE RentArrears ADD ProcessedDateTimeUtc DATETIME NULL
END
GO