IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Renters' AND COLUMN_NAME = 'RentTransactionId')
BEGIN
	ALTER TABLE Renters DROP CONSTRAINT ForeignKey_Renter_RentTransaction  

	ALTER TABLE Renters DROP COLUMN RentTransactionId
END
GO