IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MonthlyRentBatch' AND COLUMN_NAME = 'Month')
BEGIN
	ALTER TABLE MonthlyRentBatch DROP COLUMN [Month]
END
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MonthlyRentBatch' AND COLUMN_NAME = 'Year')
BEGIN
	ALTER TABLE MonthlyRentBatch DROP COLUMN [Year]
END
GO