
  IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'BookingTypes' AND COLUMN_NAME = 'NoOfPersons')
  BEGIN
	ALTER TABLE BookingTypes ADD NoOfPersons INT NOT NULL DEFAULT(0)
  END
  GO

  IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'BookingTypes' AND COLUMN_NAME = 'NoOfPersonsMax')
  BEGIN
	ALTER TABLE BookingTypes ADD NoOfPersonsMax INT NOT NULL DEFAULT(0)
  END
  GO

    IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'BookingTypes' AND COLUMN_NAME = 'BookingUrl')
  BEGIN
	ALTER TABLE BookingTypes ADD BookingUrl NVARCHAR(100) NULL
  END
  GO