IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'BookingTypes' AND COLUMN_NAME = 'Name')
BEGIN
	ALTER TABLE BookingTypes DROP COLUMN Name
END
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'BookingTypes' AND COLUMN_NAME = 'Price')
BEGIN
	ALTER TABLE BookingTypes DROP COLUMN Price
END
GO
