//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RicDatabaseUpgrader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RicDatabaseUpgrader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Update.
        /// </summary>
        internal static string Program_DrawMenu__1__Update {
            get {
                return ResourceManager.GetString("Program_DrawMenu__1__Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Create.
        /// </summary>
        internal static string Program_DrawMenu__2__Create {
            get {
                return ResourceManager.GetString("Program_DrawMenu__2__Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Exit program.
        /// </summary>
        internal static string Program_DrawMenu__3__Exit_program {
            get {
                return ResourceManager.GetString("Program_DrawMenu__3__Exit_program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating database.
        /// </summary>
        internal static string Program_Main_Creating_database {
            get {
                return ResourceManager.GetString("Program_Main_Creating_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating database.
        /// </summary>
        internal static string Program_Main_Updating_database {
            get {
                return ResourceManager.GetString("Program_Main_Updating_database", resourceCulture);
            }
        }
    }
}
