IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'accounts' AND COLUMN_NAME = 'IsSelected')
BEGIN
	ALTER TABLE accounts ADD IsSelected BIT NOT NULL DEFAULT(0)
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AuditAccounts' AND COLUMN_NAME = 'IsSelected')
BEGIN
	ALTER TABLE AuditAccounts ADD IsSelected BIT NOT NULL DEFAULT(0)
END
GO